### ISSUE TITLE
odbc doesn't build on travis language:r

### ISSUE THREAD

**Issue by AlexAxthelm** [rstats-db/odbc#53]
### Issue Description and Expected Result
When I try to build include odbc in my script, it fails to compile

### Database
N/A

### Reproducible Example
The travis build log is at: https://travis-ci.org/AlexAxthelm/DualCredit_AP_dash/builds/221429471

#### `.travis.yml`:
```yml
language: R
cache: packages
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - unixodbc
    - unixodbc-dev
    - tdsodbc
    - libsqliteodbc

script:
- Rscript -e 'rmarkdown::render(input = "ap_dc.Rmd", output_file = "index.html")'
```

#### `DESCRIPTION`:
```
Imports:
  knitr,
  DT,
  plotly,
  tidyverse,
  DBI,
  htmltools,
  broom,
  openxlsx,
  RSQLite,
  rmarkdown,
  devtools,
  secure,
  PKI,
  odbc
Remotes:
  s-u/PKI,
  hadley/secure,
  rstats-db/odbc
```

<details>
<summary>Session Info</summary>

```r
$ Rscript -e 'sessionInfo()'
R version 3.3.3 (2017-03-06)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu precise (12.04.5 LTS)
locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
attached base packages:
[1] stats     graphics  grDevices utils     datasets  base     
```
</details>
